# Generated by Django 5.0.14 on 2026-03-13 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('videos', '0003_video_channel_suggestedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allow_embed',
            field=models.BooleanField(default=True, help_text='Allow embedding on other sites'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for SEO', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Video duration in format HH:MM:SS', null=True),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='videos_vide_created_1f1e45_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['privacy', '-created_at'], name='videos_vide_privacy_315747_idx'),
        ),
    ]
