# Generated by Django 4.2.19 on 2026-03-16 20:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birthday_customuser_show_birthday_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_received_tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_sent_tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
