# Generated by Django 5.0.14 on 2026-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg_type', models.CharField(choices=[('color', 'Solid Color'), ('image', 'Image'), ('video', 'Video')], default='color', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Hex color code e.g. #0a0a0f', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='backgrounds/videos/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
