# Generated by Django 4.2.19 on 2026-03-15 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='video_file',
            new_name='video',
        ),
        migrations.AddField(
            model_name='background',
            name='accent_color',
            field=models.CharField(default='#3b82f6', help_text='Accent color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='accent_hover_color',
            field=models.CharField(default='#2563eb', help_text='Accent hover color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='border_color',
            field=models.CharField(default='#2a2a2a', help_text='Border color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='card_bg_color',
            field=models.CharField(default='#111111', help_text='Card background color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='hover_bg_color',
            field=models.CharField(default='#1a1a1a', help_text='Hover background color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='navbar_opacity',
            field=models.FloatField(default=0.95, help_text='Navbar opacity (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='background',
            name='overlay_opacity',
            field=models.FloatField(default=0.5, help_text='Overlay opacity (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='background',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Primary text color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='text_secondary_color',
            field=models.CharField(default='#a0a0a0', help_text='Secondary text color', max_length=20),
        ),
        migrations.AddField(
            model_name='background',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g., #0a0a0a', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/images/'),
        ),
    ]
