# Generated by Django 6.0.3 on 2026-03-13 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('videos', '0003_video_channel_suggestedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funding_type', models.CharField(choices=[('stars', 'Telegram Stars'), ('points', 'Platform Points'), ('crypto', 'Cryptocurrency')], default='points', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to=settings.AUTH_USER_MODEL)),
                ('suggested_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='videos.suggestedpost')),
            ],
        ),
    ]
