# Generated by Django 4.2.19 on 2026-03-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_allow_embed_video_tags_alter_video_duration_and_more'),
        ('interactions', '0002_postfunding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tip',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('mpesa', 'M-PESA')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='tip',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='videos.video'),
        ),
    ]
